name: nextjs-do-sample
services:
  - name: web
    github:
      repo: ArtiomXD/test-yaml
      branch: main
      deploy_on_push: true
    run_command: npm run start
    build_command: npm install && npm run build
    environment_slug: node-js
    instance_size_slug: basic-xxs
    instance_count: 1
    http_port: 3000
    routes:
      - path: /
    envs:
      - key: NODE_ENV
        value: production
